repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use the ref you want to point at
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--overwrite-in-place", "-e", "--atomic"]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.0
    hooks:
      - id: autoflake
        args:
          [
            "--remove-all-unused-imports",
            "--remove-duplicate-keys",
            "--remove-unused-variables",
            "--ignore-init-module-imports",
            "-i",
            "-r",
            "-vvv",
          ]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.3.0]

  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.3
    hooks:
      - id: pydocstringformatter
